BTL_LWNC_WebAmNhac/Models/Song.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace BTL_LWNC_WebAmNhac.Models
{
    public class Song
    {
        [Key]
        public int ID { get; set; }
        public string? Name { get; set; }
        [ForeignKey("Artist")]
        public int ArtistID { get; set; }
        public string? Lyric { get; set; }

        public string? Thumbnail { get; set; }
        public string? Url { get; set; }

        [ForeignKey("Genre")]
        public int GenreID { get; set; }
        public int ViewCount { get; set; }

        public virtual Artist? Artist { get; set; }

        public virtual Genre? Genre { get; set; }

        public virtual ICollection<PlaylistDetail> PlaylistDetails { get; set; } = new List<PlaylistDetail>();

    }
}

BTL_LWNC_WebAmNhac/Controllers/SongsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BTL_LWNC_WebAmNhac.Data;
using BTL_LWNC_WebAmNhac.Models;
using Microsoft.AspNetCore.Authorization;
using BTL_LWNC_WebAmNhac.Models.ViewModels;

namespace BTL_LWNC_WebAmNhac.Controllers
{
    public class SongsController : Controller
    {
        private readonly BTL_LWNC_WebAmNhacContext _context;
        public int pageSize = 5;

        public SongsController(BTL_LWNC_WebAmNhacContext context)
        {
            _context = context;
        }

        // GET: Songs
        
        public IActionResult Index(int productPage=1)
        {
            return View(
                new SongListViewModel
                {
                    Songs = _context.Song.Include(s => s.Artist).Include(s => s.Genre)
                    .Skip((productPage - 1) * pageSize)
                    .Take(pageSize),
                    PagingInfo = new PagingInfo
                    {
                        ItemsPerPage = pageSize,
                        CurrentPage = productPage,
                        TotalItems = _context.Song.Count()
                    }
                }
                );
        }

        [HttpPost]
        public IActionResult Search(string keywords)
        {
            return View(_context.Song.Include(s => s.Artist).Include(s => s.Genre)
                    .Where(s=>s.Name.Contains(keywords)));
        }
        [HttpPost]
        public IActionResult SearchByGenre(string keywords)
        {
            return View(_context.Song.Include(s => s.Artist).Include(s => s.Genre)
                    .Where(s => s.Genre.Name.Contains(keywords)));
        }
        public IActionResult ShowSongByGenreId(int id)
        {
            var SongByGenre =_context.Song
                .Include(s => s.Artist).Include(s => s.Genre)
                .AsNoTracking()
                .Where(x => x.GenreID == id)
                .OrderBy(x => x.Name).ToList();
            return View("Search",SongByGenre);
        }
        // GET: Songs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Song == null)
            {
                return NotFound();
            }

            var song = await _context.Song
                .Include(s => s.Artist)
                .Include(s => s.Genre)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (song == null)
            {
                return NotFound();
            }
                // Increment the view count
                if(song.ViewCount == null)
            {
                song.ViewCount=0;
            }
                song.ViewCount++;
                // Update the database
                _context.SaveChanges();
            return View(song);
        }

        // GET: Songs/Create
        [Authorize(Roles ="Admin")]
        public IActionResult Create()
        {
            ViewData["ArtistID"] = new SelectList(_context.Set<Artist>(), "ID", "Name");
            ViewData["GenreID"] = new SelectList(_context.Set<Genre>(), "ID", "Name");
            return View();
        }
        [Authorize(Roles = "Admin")]
        // POST: Songs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,ArtistID,Lyric,Thumbnail,Url,GenreID")] Song song)
        {
            if (ModelState.IsValid)
            {
                _context.Add(song);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistID"] = new SelectList(_context.Set<Artist>(), "ID", "Name", song.ArtistID);
            ViewData["GenreID"] = new SelectList(_context.Set<Genre>(), "ID", "Name", song.GenreID);
            return View(song);
        }
        [Authorize(Roles = "Admin")]
        // GET: Songs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Song == null)
            {
                return NotFound();
            }

            var song = await _context.Song.FindAsync(id);
            if (song == null)
            {
                return NotFound();
            }
            ViewData["ArtistID"] = new SelectList(_context.Set<Artist>(), "ID", "Name", song.ArtistID);
            ViewData["GenreID"] = new SelectList(_context.Set<Genre>(), "ID", "Name", song.GenreID);
            return View(song);
        }
        [Authorize(Roles = "Admin")]
        // POST: Songs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,ArtistID,Lyric,Thumbnail,Url,GenreID")] Song song)
        {
            if (id != song.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(song);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SongExists(song.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistID"] = new SelectList(_context.Set<Artist>(), "ID", "Name", song.ArtistID);
            ViewData["GenreID"] = new SelectList(_context.Set<Genre>(), "ID", "Name", song.GenreID);
            return View(song);
        }
        [Authorize(Roles = "Admin")]
        // GET: Songs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Song == null)
            {
                return NotFound();
            }

            var song = await _context.Song
                .Include(s => s.Artist)
                .Include(s => s.Genre)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (song == null)
            {
                return NotFound();
            }

            return View(song);
        }
        [Authorize(Roles = "Admin")]
        // POST: Songs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Song == null)
            {
                return Problem("Entity set 'BTL_LWNC_WebAmNhacContext.Song'  is null.");
            }
            var song = await _context.Song.FindAsync(id);
            if (song != null)
            {
                _context.Song.Remove(song);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin")]
        private bool SongExists(int id)
        {
          return (_context.Song?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

BTL_LWNC_WebAmNhac/Views/Songs/Create.cshtml
@model BTL_LWNC_WebAmNhac.Models.Song

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Song</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtistID" class="control-label"></label>
                <select asp-for="ArtistID" class ="form-control" asp-items="ViewBag.ArtistID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Lyric" class="control-label"></label>
                <input asp-for="Lyric" class="form-control" />
                <span asp-validation-for="Lyric" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Thumbnail" class="control-label"></label>
                <input asp-for="Thumbnail" class="form-control" />
                <span asp-validation-for="Thumbnail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenreID" class="control-label"></label>
                <select asp-for="GenreID" class ="form-control" asp-items="ViewBag.GenreID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BTL_LWNC_WebAmNhac/Views/Songs/Delete.cshtml
@model BTL_LWNC_WebAmNhac.Models.Song

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Song</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lyric)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lyric)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thumbnail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Thumbnail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Url)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.ID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BTL_LWNC_WebAmNhac/Views/Songs/Details.cshtml
@model BTL_LWNC_WebAmNhac.Models.Song

@{
    ViewData["Title"] = "Details";
    Layout = "_Songs";
}


@if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("admin")))
{
    <h1>Details</h1>
    <div>
        <h4>Song</h4>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Lyric)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Lyric)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Thumbnail)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Thumbnail)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Url)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Url)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Artist)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Artist.Name)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Genre)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Genre.Name)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
}
else
{
    <div class="audio-title"><h2>@Model.Name</h2></div>
    <div class="audio-playbar">
        <div class="audio-row">

            <img src="@Model.Thumbnail" style="width:100px">
        </div>

        <div class="audio-row">
            <audio id="custom-audio-player" src="@Url.Content(Model.Url)" style="display: none;"></audio>
            <div class="time-container">
                <input type="range" id="timeSlider" name="timeSlider" min="0" step="1" value="0" max="100" />
                <div class="buffer-bar" id="bufferBar" style="display:none"></div>
            </div>
        </div>

        <div class="audio-row button-container">
            <div class="left-button" id="play-button">
                <i class="fa fa-play" aria-hidden="true"></i>
                <i class="fa fa-pause" aria-hidden="true"></i>
            </div>
            <div class="right-button">
                <select id="speed-select">
                    <option value="1">Normal Speed</option>
                    <option value="1.5">1.5x Speed</option>
                    <option value="2">2x Speed</option>
                </select>
            </div>
            <div class="right-button" id="volume-container">
                <i class="fa fa-volume-up" id="volume-button" aria-hidden="true"></i>
                <input type="range" id="volume" name="volume" min="0" max="1" step="0.01" value="1">
            </div>
        </div>
    </div>
    <div class="download-container">
    <i id="download-button" class="fa fa-download" aria-hidden="true"></i>
    <p>Tải xuống</p>
</div>

    @if (User.Identity.IsAuthenticated && (User.IsInRole("User") || User.IsInRole("user")))
    {
        <div class="add-playlist" onclick="showList(event,'@Model.ID')" style="margin:10px 0px">
            <i class="fa fa-plus-square-o" aria-hidden="true" onclick="showList(event, '@Model.ID');addPlaylist(event,'@Model.ID')"></i>
            Thêm vào playlist
        </div>
    }

    <h5>Lời bài hát</h5>
    <div class="lyric-container">
        <p>@Model.Lyric</p>
    </div>
}

<style>
    .audio-playbar {
        width: 900px;
        display: flex;
        flex-direction: column;
        background-color: #f0f0f0;
        padding: 10px;
    }

    .audio-row {
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin-bottom: 10px;
    }

    .audio-title {
        font-weight: bold;
    }

    #custom-audio-player {
        width: 100%;
    }

    .left-button, .right-button {
        cursor: pointer;
        padding: 5px;
    }

    #play-button .fa-pause {
        display: none;
    }

    #play-button.playing .fa-pause {
        display: inline-block;
    }

    #play-button.playing .fa-play {
        display: none;
    }

    #speed-select, #volume-container {
        margin-left: 10px;
    }

    /* Update styles for the button container */
    .button-container {
        display: flex;
        align-items: center;
    }

    #forward-button {
        margin-right: auto;
    }

    .right-button {
        margin-left: 0;
    }


    .time-container {
        margin-top: 10px;
        position: relative;
        width: 100%;
    }

    #timeSlider {
        width: 100%;
    }

    .buffer-bar {
        position: absolute;
        top: 0;
        left: 0;
        height: 5px;
        background-color: #ccc;
        width: 0;
    }
</style>

@await Component.InvokeAsync("UserPlaylist")
<script>
    function addPlaylist(event, songID) {
        console.log("go to func...");

        // Unbind click event to avoid multiple bindings
        jQuery(".userPlaylist").off("click", ".list-item");

        jQuery(".userPlaylist").on("click", ".list-item", function () {
            var playlistID = jQuery(this).data("id");
            console.log("playlistID add to playlist:", playlistID);
            console.log("songID add to playlist:", songID);
            var url = '/PlaylistDetails/addToPlaylistDetail/?playlistID=' + playlistID + '&songID=' + songID;
            jQuery.ajax({
                type: "POST",
                url: url,
                dataType: "json",
                success: function (data) {
                    if (data.success) {
                        alert("Thêm thành công");
                        console.log("success add to playlist detail");
                    } else {
                        console.log("fail01");
                        alert("Đã có trong playlist");
                    }
                },
                error: function () {
                    console.log("fail00");
                    alert("Thêm thất bại. Xin vui lòng thử lại!");
                }
            });
        });
    }
</script>

<script src="/js/showPlaylist.js"></script>

<script>
    const $ = document.querySelector.bind(document);
    const $$ = document.querySelectorAll.bind(document);

    const playBtn = $('#play-button')
    const audio = $('#custom-audio-player')
    const player = $('#play-button')
    const progress = $('#timeSlider')
    const volume = $('#volume')
    const speed = $('#speed-select')

    const app = {
        isPlaying: false,
        handleEvents: function () {
            playBtn.onclick = function () {
                if (app.isPlaying) {
                    audio.pause()
                } else {
                    audio.play()
                }
            }
            audio.onplay = function () {
                app.isPlaying = true
                player.classList.add('playing')
            }
            audio.onpause = function () {
                app.isPlaying = false
                player.classList.remove('playing')
            }
            audio.ontimeupdate = function () {
                if (audio.duration) {
                    const progressPercent = Math.floor((audio.currentTime / audio.duration) * 100);
                    progress.value = progressPercent;
                }
            };
            progress.oninput = function (e) {
                const seekTime = (audio.duration / 100) * e.target.value;
                audio.currentTime = seekTime;
            };
            volume.oninput = function () {
                audio.volume = volume.value
            }
            speed.onchange = function () {
                audio.playbackRate = parseFloat(speed.value)
            }

        },
        start: function () {
            this.handleEvents()
        }
    }
    app.start()
</script>

@* //Xu ly tai xuong *@
<script>
    function loc_xoa_dau(str) {
        // Gộp nhiều dấu space thành 1 space
        str = str.replace(/\s+/g, ' ');
        // loại bỏ toàn bộ dấu space (nếu có) ở 2 đầu của chuỗi
        str = str.trim();
        // bắt đầu xóa dấu tiếng việt  trong chuỗi
        str = str.replace(/à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ/g, "a");
        str = str.replace(/è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ/g, "e");
        str = str.replace(/ì|í|ị|ỉ|ĩ/g, "i");
        str = str.replace(/ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ/g, "o");
        str = str.replace(/ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ/g, "u");
        str = str.replace(/ỳ|ý|ỵ|ỷ|ỹ/g, "y");
        str = str.replace(/đ/g, "d");
        str = str.replace(/À|Á|Ạ|Ả|Ã|Â|Ầ|Ấ|Ậ|Ẩ|Ẫ|Ă|Ằ|Ắ|Ặ|Ẳ|Ẵ/g, "A");
        str = str.replace(/È|É|Ẹ|Ẻ|Ẽ|Ê|Ề|Ế|Ệ|Ể|Ễ/g, "E");
        str = str.replace(/Ì|Í|Ị|Ỉ|Ĩ/g, "I");
        str = str.replace(/Ò|Ó|Ọ|Ỏ|Õ|Ô|Ồ|Ố|Ộ|Ổ|Ỗ|Ơ|Ờ|Ớ|Ợ|Ở|Ỡ/g, "O");
        str = str.replace(/Ù|Ú|Ụ|Ủ|Ũ|Ư|Ừ|Ứ|Ự|Ử|Ữ/g, "U");
        str = str.replace(/Ỳ|Ý|Ỵ|Ỷ|Ỹ/g, "Y");
        str = str.replace(/Đ/g, "D");
        return str;
    }
    var songName = loc_xoa_dau('@Html.Raw(@Model.Name)').replace(/\s/g, '');
    var downloadButton = document.getElementById('download-button');

    // Now modelName contains the value of @Model.Name as a JavaScript string
    downloadButton.addEventListener('click', function () {
        // Add logic to trigger the download of the audio file
        var audioFileUrl = '@Url.Content(Model.Url)';
        var a = document.createElement('a');
        a.href = audioFileUrl;
        a.download = songName + ".mp3"; // Set the desired file name
        a.style.display = 'none';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
    });

</script>

BTL_LWNC_WebAmNhac/Views/Songs/Edit.cshtml
@model BTL_LWNC_WebAmNhac.Models.Song

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Song</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtistID" class="control-label"></label>
                <select asp-for="ArtistID" class="form-control" asp-items="ViewBag.ArtistID"></select>
                <span asp-validation-for="ArtistID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lyric" class="control-label"></label>
                <input asp-for="Lyric" class="form-control" />
                <span asp-validation-for="Lyric" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Thumbnail" class="control-label"></label>
                <input asp-for="Thumbnail" class="form-control" />
                <span asp-validation-for="Thumbnail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenreID" class="control-label"></label>
                <select asp-for="GenreID" class="form-control" asp-items="ViewBag.GenreID"></select>
                <span asp-validation-for="GenreID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BTL_LWNC_WebAmNhac/Views/Songs/Search.cshtml
@model IEnumerable<BTL_LWNC_WebAmNhac.Models.Song>

@using System.Security.Claims;
@{
    ViewData["Title"] = "Index";
    Layout = "_Songs";
}
@if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("admin")))
{
    <div>
        <p>
            <a asp-action="Create">Create New</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        ID
                    </th>
                    <th>
                        Tên bài hát
                    </th>
                    <th>
                        Nghệ sĩ
                    </th>
                    <th>
                        Lời bài hát
                    </th>
                    <th>
                        Ảnh bìa
                    </th>
                    <th>
                        Nguồn
                    </th>
                    <th>
                        Thể loại
                    </th>
                    <th>
                        Lượt xem
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Artist.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Lyric)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Thumbnail)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Url)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Genre.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ViewCount)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}

else
{
    <div class="music-box">
        @foreach (var item in Model)
        {
            <div class="music-div">
                <div class="music-info">
                    <div class="music-img">
                        <img src="@item.Thumbnail">
                    </div>
                    <div class="music-name">
                        <h6>@item.Name</h6>
                        <p>@item.Artist?.Name</p>
                    </div>
                    <div class="music-genre">
                        <p>@item.Genre?.Name</p>
                    </div>
                    <div class="music-action">
                        <div id="playIcon" onclick="redirectToDetails('@item.ID')"><i class="fa fa-play" aria-hidden="true"></i></div>
                        <div id="playInNewTab" onclick="playInNewTab('@item.ID')"><i class="fa fa-clone" aria-hidden="true"></i></div>
                        @if (User.Identity.IsAuthenticated && (User.IsInRole("User") || User.IsInRole("user")))
                        {
                            <div class="add-playlist" onclick="showList(event,'@item.ID')">
                                <i class="fa fa-plus-square-o" aria-hidden="true" onclick="showList(event, '@item.ID');addPlaylist(event,'@item.ID')"></i>
                            </div>
                        }
                    </div>
                </div>
                <hr>
            </div>
        }
    </div>

@await Component.InvokeAsync("UserPlaylist")
<script>
    function addPlaylist(event, songID) {
        console.log("go to func...");
        $(".userPlaylist").on("click", ".list-item", function () {
            var playlistID = $(this).data("id");
            console.log("playlistID add to playlist:", playlistID);
            console.log("songID add to playlist:", songID);
            var url = '/PlaylistDetails/addToPlaylistDetail/?playlistID=' + playlistID + '&songID=' + songID;
            $.ajax({
                type: "POST",
                url: url,
                dataType: "json",
                success: function (data) {
                    if (data.success) {
                        alert("add successfully");
                        console.log("success add to playlist detail");
                    } else {
                        console.log("fail01");
                        alert("Failed to add");
                    }
                },
                error: function () {
                    console.log("fail00");
                    alert("Have a error while adding");
                }
            });
        });
    }
</script>

<script src="/js/showPlaylist.js"></script>
}

BTL_LWNC_WebAmNhac/Views/Songs/SearchByGenre.cshtml
@model IEnumerable<BTL_LWNC_WebAmNhac.Models.Song>
@{
    ViewData["Title"] = "Index";
}
<div class="title">
    <h4>Danh sách bài hát theo @Model.FirstOrDefault().Genre.Name</h4>
</div>
<div class="playlist-container">
    @foreach (var item in Model)
    {
        <div class="playlist-div">
            <div class="image-container">
                <img src="@item.Thumbnail" class="playlist-img" alt="" runat="server" />
            </div>
            <!-- name detail -->
            <div class="playlist-title">
                <div class="text-bold">
                    <a href="@Url.Action("Details", "Songs",new { id=item.ID})">
                        @item.Name
                    </a>
                </div>
                <div class="text-thin">
                    @item.Genre.Name
                </div>
            </div>

        </div>
    }
</div>