BTL_LWNC_WebAmNhac/Models/Playlist.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BTL_LWNC_WebAmNhac.Models
{
    public class Playlist
    {
        [Key]
        public int ID { get; set; }

        [DisplayName("Tên")]
        public string? Name { get; set; }
        [DisplayName("Mô tả")]
        public string? Detail { get; set; }
        [DisplayName("Ảnh bìa")]
        public string? Thumbnail { get; set; }
        [ForeignKey("User")]
        public int UserID { get; set; }
        public int ViewCount { get; set; }

        public virtual User? User { get; set; }

        public virtual ICollection<PlaylistDetail> PlaylistDetails { get; set; } = new List<PlaylistDetail>();
    }
}

BTL_LWNC_WebAmNhac/Models/UserPlaylist.cs
using BTL_LWNC_WebAmNhac.Data;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BTL_LWNC_WebAmNhac.Models
{
    public class UserPlaylist:ViewComponent
    {
        private readonly BTL_LWNC_WebAmNhacContext _context;

        public UserPlaylist(BTL_LWNC_WebAmNhacContext context)
        {
            _context = context;
        }
        public IViewComponentResult Invoke()
        {
            
            if (User.Identity.IsAuthenticated)
            {
                var userClaims = User.Identity as ClaimsIdentity;
                var userID = int.Parse(userClaims.FindFirst(ClaimTypes.NameIdentifier).Value); ;
                var username = User.Identity.Name;
                return View(_context.Playlist.Where(p => p.UserID == userID).ToList());
            }
            
            else
            {
                var defaultModel = new List<Playlist>();
                return View(defaultModel);
            }
        }
    }
}

BTL_LWNC_WebAmNhac/Controllers/PlaylistDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BTL_LWNC_WebAmNhac.Data;
using BTL_LWNC_WebAmNhac.Models;
using Microsoft.AspNetCore.Authorization;

namespace BTL_LWNC_WebAmNhac.Controllers
{
    public class PlaylistDetailsController : Controller
    {
        private readonly BTL_LWNC_WebAmNhacContext _context;

        public PlaylistDetailsController(BTL_LWNC_WebAmNhacContext context)
        {
            _context = context;
        }

        // GET: PlaylistDetails
        public async Task<IActionResult> Index()
        {
            var bTL_LWNC_WebAmNhacContext = _context.PlaylistDetail?.Include(p => p.Playlist).Include(p=>p.Song);
            return bTL_LWNC_WebAmNhacContext != null ?
                        View(await bTL_LWNC_WebAmNhacContext.ToListAsync()) :
                        Problem("Entity set 'BTL_LWNC_WebAmNhacContext.PlaylistDetail'  is null.");
        }

        // GET: PlaylistDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewBag.playlistId = id;
            if (id == null || _context.PlaylistDetail == null)
            {
                return NotFound();
            }

            var playlistDetail = await _context.PlaylistDetail
                .Include(p => p.Playlist)
                .Include(p => p.Song).ThenInclude(s => s.Artist)
                .Include(p => p.Song).ThenInclude(s => s.Genre)
                .Where(m => m.PlaylistID == id)
                .ToListAsync();
            if (playlistDetail == null)
            {
                return NotFound();
            }
            var playlist = _context.Playlist.Find(id);
            if(playlist.ViewCount <0)
            {
                playlist.ViewCount = 0;
            }
            playlist.ViewCount++;
            // Update the database
            _context.SaveChanges();

            return View(playlistDetail);
        }
        public async Task<IActionResult> Playlist(int? id)
        {
            if (id == null || _context.PlaylistDetail == null)
            {
                return NotFound();
            }

            var playlistDetail = await _context.PlaylistDetail
                .Include(p => p.Playlist)
                .Include(p => p.Song).ThenInclude(s => s.Artist)
                .Include(p => p.Song).ThenInclude(s => s.Genre)
                .Where(m => m.PlaylistID == id)
                .ToListAsync();
            if (playlistDetail == null)
            {
                return NotFound();
            }
            var playlist = _context.Playlist.Find(id);
            if (playlist.ViewCount == null)
            {
                playlist.ViewCount = 0;
            }
            playlist.ViewCount++;
            // Update the database
            _context.SaveChanges();

            return View(playlistDetail);
        }
        [Authorize(Roles = "Admin,User")]
        [HttpPost]
        public async Task<JsonResult> addToPlaylistDetail(int playlistID, int songID)
        {
            var playlistDetail = new PlaylistDetail()
            {
                PlaylistID = playlistID,
                SongID = songID
            };
/*            if (PlaylistDetailExists(playlistID, songID))
            {
                return Json(new { success = false, errorMessage = "Bài hát đã có trong playlist" });
            }*/

            _context.PlaylistDetail.Add(playlistDetail);

            var saveChangesResult = await _context.SaveChangesAsync();

            if (saveChangesResult > 0)
            {
                return Json(new { success = true });
            }
            else
            {
                return Json(new { success = false, errorMessage = "Failed to add to the database." });
            }
        }

        // GET: PlaylistDetails/Create
        [Authorize(Roles = "Admin,User")]
        public IActionResult Create()
        {
            ViewData["PlaylistID"] = new SelectList(_context.Set<Playlist>(), "ID", "Name");
            ViewData["SongID"] = new SelectList(_context.Set<Song>(), "ID", "Name");
            return View();
        }

        // POST: PlaylistDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin,User")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlaylistID,SongID")] PlaylistDetail playlistDetail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(playlistDetail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(playlistDetail);
        }
        [Authorize(Roles = "Admin,User")]
        [HttpPost]
        public async Task<JsonResult> XoaBaiHat(int playlistid, int songid)
        {

            var playlistDetail = await _context.PlaylistDetail.FindAsync(playlistid, songid);

            if (playlistDetail != null)
            {
                _context.PlaylistDetail.Remove(playlistDetail);
            }
            else
            {
                return Json(new { success = false });
            }

            // Use SaveChangesAsync for asynchronous operation
            await _context.SaveChangesAsync();

            return Json(new { success = true });
        }
        // GET: PlaylistDetails/Delete/5
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Delete(int? playlistID, int? songID)
        {
            if (playlistID == null || songID==null || _context.PlaylistDetail == null)
            {
                return NotFound();
            }

            var playlistDetail = await _context.PlaylistDetail
                .Include(x => x.Playlist).Include(x => x.Song)
                .FirstOrDefaultAsync(m => m.PlaylistID == playlistID && m.SongID==songID );
            if (playlistDetail == null)
            {
                return NotFound();
            }

            return View(playlistDetail);
        }

        // POST: PlaylistDetails/Delete/5
        [Authorize(Roles = "Admin,User")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int playlistID, int songID)
        {
            if (_context.PlaylistDetail == null)
            {
                return Problem("Entity set 'BTL_LWNC_WebAmNhacContext.PlaylistDetail'  is null.");
            }
            var playlistDetail = await _context.PlaylistDetail.FindAsync(playlistID,songID);
            if (playlistDetail != null)
            {
                _context.PlaylistDetail.Remove(playlistDetail);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        private JsonResult CheckExitInPlaylist(int id)
        {
            var boolexit= (_context.PlaylistDetail?.Any(e => e.SongID == id)).GetValueOrDefault();
            if (boolexit){
                return Json(new { success = true });
            }
            else {
                return Json(new { success = false });
            }
        }

        [Authorize(Roles = "Admin,User")]
        private bool PlaylistDetailExists(int playlistID,int songID)
        {
          return (_context.PlaylistDetail?.Any(e => e.PlaylistID == playlistID && e.SongID==songID)).GetValueOrDefault();
        }
    }
}

BTL_LWNC_WebAmNhac/Controllers/PlaylistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BTL_LWNC_WebAmNhac.Data;
using BTL_LWNC_WebAmNhac.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace BTL_LWNC_WebAmNhac.Controllers
{
    public class PlaylistsController : Controller
    {
        private readonly BTL_LWNC_WebAmNhacContext _context;

        public PlaylistsController(BTL_LWNC_WebAmNhacContext context)
        {
            _context = context;
        }

        // GET: Playlists
        public async Task<IActionResult> Index()
        {
            var bTL_LWNC_WebAmNhacContext = _context.Playlist?.Include(p => p.User);
            return View(await bTL_LWNC_WebAmNhacContext.ToListAsync());
        }
        public async Task<IActionResult> UserPlaylist()
        {
            var userClaims = User.Identity as ClaimsIdentity;
            if (userClaims.IsAuthenticated)
            {
                var usernameClaim = int.Parse(userClaims.FindFirst(ClaimTypes.NameIdentifier).Value);
                var userPlaylists = _context.Playlist.Include(p => p.User).Where(p => p.UserID == usernameClaim).ToListAsync();
                return View(await userPlaylists);
            }
            else
            {
                return RedirectToAction("Login","Users");
            }

        }

        // GET: Playlists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Playlist == null)
            {
                return NotFound();
            }

            var playlist = await _context.Playlist
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (playlist == null)
            {
                return NotFound();
            }

            return View(playlist);
        }

        // GET: Playlists/Create
        [Authorize(Roles ="Admin,User")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Playlists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin,User")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("Name,Detail,Thumbnail")] Playlist playlist)
        {
            if (ModelState.IsValid)
            {
                var newPlaylist = new Playlist()
                {
                    Name = playlist.Name,
                    Detail = playlist.Detail,
                    Thumbnail = playlist.Thumbnail,
                    UserID = id,
                    ViewCount = 0
                };
                _context.Add(newPlaylist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(UserPlaylist));
            }
            return View(playlist);
        }

        // GET: Playlists/Edit/5
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Playlist == null)
            {
                return NotFound();
            }

            var playlist = await _context.Playlist.FindAsync(id);
            if (playlist == null)
            {
                return NotFound();
            }
            return View(playlist);
        }

        // POST: Playlists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin,User")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Detail,Thumbnail,UserID,ViewCount")] Playlist playlist)
        {
            if (id != playlist.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(playlist);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlaylistExists(playlist.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(UserPlaylist));
            }
            return View(playlist);
        }

        // GET: Playlists/Delete/5
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Playlist == null)
            {
                return NotFound();
            }

            var playlist = await _context.Playlist
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (playlist == null)
            {
                return NotFound();
            }

            return View(playlist);
        }

        // POST: Playlists/Delete/5
        [Authorize(Roles = "Admin,User")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Playlist == null)
            {
                return Problem("Entity set 'BTL_LWNC_WebAmNhacContext.Playlist'  is null.");
            }
            var playlist = await _context.Playlist.FindAsync(id);
            if (playlist != null)
            {
                _context.Playlist.Remove(playlist);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(UserPlaylist));
        }
        [Authorize(Roles = "Admin,User")]
        private bool PlaylistExists(int id)
        {
          return (_context.Playlist?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

BTL_LWNC_WebAmNhac/Views/Playlists/Create.cshtml
@model BTL_LWNC_WebAmNhac.Models.Playlist

@{
    ViewData["Title"] = "Create";
}

<h1>Create User Playlist</h1>

<h4>Playlist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Detail" class="control-label"></label>
                <input asp-for="Detail" class="form-control" />
                <span asp-validation-for="Detail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Thumbnail" class="control-label"></label>
                <input asp-for="Thumbnail" class="form-control" />
                <span asp-validation-for="Thumbnail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BTL_LWNC_WebAmNhac/Views/Playlists/Delete.cshtml
@model BTL_LWNC_WebAmNhac.Models.Playlist

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Playlist</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Detail)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Detail)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Thumbnail)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Thumbnail)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ViewCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ViewCount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.ID)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BTL_LWNC_WebAmNhac/Views/Playlists/Details.cshtml
@model BTL_LWNC_WebAmNhac.Models.Playlist

@{
    ViewData["Title"] = "Details";
}

<h1>Chi tiết</h1>

<div>
    <h4>Playlist</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Detail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Detail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thumbnail)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Model.Thumbnail" style="max-width:200px"/>
        </dd>
        <dt class = "col-sm-2">
            Người tạo:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BTL_LWNC_WebAmNhac/Views/Playlists/Edit.cshtml
@model BTL_LWNC_WebAmNhac.Models.Playlist

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Playlist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <input type="hidden" asp-for="UserID" class="form-control" />
            <input type="hidden" asp-for="ViewCount" class="form-control" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Detail" class="control-label"></label>
                <input asp-for="Detail" class="form-control" />
                <span asp-validation-for="Detail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Thumbnail" class="control-label"></label>
                <input asp-for="Thumbnail" class="form-control" />
                <span asp-validation-for="Thumbnail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BTL_LWNC_WebAmNhac/Views/Playlists/Index.cshtml
@model IEnumerable<BTL_LWNC_WebAmNhac.Models.Playlist>

@{
    ViewData["Title"] = "Index";
}
@if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("admin")))
{
    <h1>Index</h1>

    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Tên playlist
                </th>
                <th>
                    Mô tả
                </th>
                <th>
                    Ảnh bìa
                </th>
                <th>
                    Người đăng
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Detail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Thumbnail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.User.Name)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    @await Component.InvokeAsync("Option")
    <div class="title">
        <h4>Tất cả playlist</h4>
    </div>
    <div class="playlist-container">
        @foreach (var item in Model)
        {
            <div class="playlist-div">
                <div class="image-container">
                    <img src="@item.Thumbnail" class="playlist-img" alt="" runat="server" />
                </div>
                <!-- name detail -->
                <div class="playlist-title">
                    <div class="text-bold">
                        <a href="@Url.Action("Playlist", "PlaylistDetails",new { id=item.ID})">
                            @item.Name
                        </a>
                    </div>
                    <div class="text-thin">
                        @item.Detail
                    </div>
                </div>
            </div>
        }
    </div>

}

BTL_LWNC_WebAmNhac/Views/Playlists/UserPlaylist.cshtml
@using System.Security.Claims;
@model IEnumerable<BTL_LWNC_WebAmNhac.Models.Playlist>

@{
    ViewData["Title"] = "Index";
    var userID = -1;
    if (User.Identity.IsAuthenticated)
    {
        var userClaims = User.Identity as ClaimsIdentity;
        userID = int.Parse(userClaims.FindFirst(ClaimTypes.NameIdentifier).Value);
    }
}

<h1>Thư viện</h1>

@if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("admin")))
{
    <table class="table table-sm">
        @foreach (var claim in User.Claims)
        {
            <tr>
                <td>@claim.Type</td>
                <td>@claim.Value</td>
            </tr>
        }
    </table>

    <p>
        <a asp-controller="Playlists" asp-action="Create" asp-route-id="@userID">Create New Playlist</a>
    </p>

    <table class="table">
        <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Tên playlist
                </th>
                <th>
                    Mô tả
                </th>
                <th>
                    Ảnh bìa
                </th>
                <th>
                    Người đăng
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Where(p => p.User.ID == userID))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Detail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Thumbnail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.User.Name)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                        <a asp-controller="PlaylistDetails" asp-action="Details" asp-route-id="@item.ID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
@if (User.Identity.IsAuthenticated && (User.IsInRole("User") || User.IsInRole("user")))
{
    <p>
        <a asp-controller="Playlists" asp-action="Create" asp-route-id="@userID">Create New Playlist</a>
    </p>
    <div class="playlist-container">
        @foreach (var item in Model)
        {
            <div class="playlist-div">
                <div class="image-container">
                    <img src="@item.Thumbnail" class="playlist-img" alt="" runat="server" />
                </div>
                <!-- name detail -->
                <div class="playlist-title">
                    <div class="text-bold">
                        <a href="@Url.Action("Details", "PlaylistDetails",new { id=item.ID})">
                            @item.Name
                        </a>
                    </div>
                    <div class="text-thin">
                        @item.Detail
                    </div>
                </div>
            </div>
        }
    </div>
}